### ISSUE TITLE
crash when launching

### ISSUE THREAD

**Issue by mmmthepotatogod** [Hellish-Mods/Powah-Overcharged#8] opened 2023-11-23 17:31 UTC
so, basicly, im using the latest forge 1.16.5, and the mod just simply crashes the game on launch, with basicly no trace in the latest.log, and no crash report either. crash code 1.
what do i do with it...?
im using the mod version of powah-2.3o1.1.jar

**Comment by Gcat101** [comment] 2023-11-23 17:33
@RealRainbuu

**Comment by Gcat101** [comment] 2023-12-05 21:00
Wasn't able to reproduce but have fixed a separate bug that might've been causing it, can you try to replace the jar with [the new version available on cf](https://legacy.curseforge.com/minecraft/mc-mods/powah-overcharged/files/4930391) and post an update?

**Comment by Gcat101** [comment] 2023-12-05 21:00
also please post still post your logs and modlist

**Comment by Gcat101** [comment] 2023-12-05 21:12
was able to get a crash [when launching the game with IAP, if you have that](https://paste.ee/p/2eBuw)

related: #7

**Comment by mmmthepotatogod** [comment] 2023-12-05 21:27
Currently away from home. Should be able to update you in about a day. Sorry.. also, i do not use the IAP addon 😲

**Comment by Gcat101** [comment] 2023-12-05 22:03
Ah, seems like a different bug then. Alr ty

**Comment by mmmthepotatogod** [comment] 2023-12-06 06:53
nop, still crashing with code 1.
ill share the latest.log:
[06דצמ2023 08:48:23.166] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, mmm123456, --version, 1.16.5-forge-36.2.39, --gameDir, C:\Users\user\AppData\Roaming\.minecraft, --assetsDir, C:\Users\user\AppData\Roaming\.minecraft\assets, --assetIndex, 1.16, --uuid, d6213c94aedb4e90bdb3f935934879e0, --accessToken, ????????, --userType, msa, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 36.2.39, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210115.111550]
[06דצמ2023 08:48:23.171] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 8.1.3+8.1.3+main-8.1.x.c94d18ec starting: java version 1.8.0_51 by Oracle Corporation
[06דצמ2023 08:48:23.186] [main/WARN] [cpw.mods.modlauncher.SecureJarHandler/]: LEGACY JDK DETECTED, SECURED JAR HANDLING DISABLED
[06דצמ2023 08:48:30.945] [main/INFO] [net.minecraftforge.fml.loading.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[06דצמ2023 08:48:30.973] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Users/user/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=CLIENT
[06דצמ2023 08:48:32.721] [main/INFO] [STDERR/]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 2:141 token recognition error at: ';'
[06דצמ2023 08:48:32.751] [main/INFO] [STDERR/]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 13:0 token recognition error at: '`'
[06דצמ2023 08:48:32.798] [main/INFO] [STDERR/]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 1:0 token recognition error at: '/'
[06דצמ2023 08:48:32.799] [main/INFO] [STDERR/]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 1:1 token recognition error at: '/'
[06דצמ2023 08:48:32.803] [main/INFO] [STDERR/]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 59:57 token recognition error at: 's'
[06דצמ2023 08:48:32.828] [main/INFO] [STDERR/]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 1:0 token recognition error at: '~'
[06דצמ2023 08:48:33.413] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config modid.mixin.json
[06דצמ2023 08:48:33.413] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
[06דצמ2023 08:48:33.413] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
[06דצמ2023 08:48:33.413] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
[06דצמ2023 08:48:33.413] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.addConfig(MixinPlatformManager.java:262)
[06דצמ2023 08:48:33.414] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinPlatformAgentDefault.prepare(MixinPlatformAgentDefault.java:46)
[06דצמ2023 08:48:33.414] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinContainer.prepare(MixinContainer.java:122)
[06דצמ2023 08:48:33.414] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.createContainerFor(MixinPlatformManager.java:144)
[06דצמ2023 08:48:33.414] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.addContainer(MixinPlatformManager.java:134)
[06דצמ2023 08:48:33.414] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.addNestedContainers(MixinPlatformManager.java:152)
[06דצמ2023 08:48:33.414] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.scanForContainers(MixinPlatformManager.java:213)
[06דצמ2023 08:48:33.414] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:186)
[06דצמ2023 08:48:33.414] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:202)
[06דצמ2023 08:48:33.414] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:201)
[06דצמ2023 08:48:33.414] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:195)
[06דצמ2023 08:48:33.414] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$9(LaunchPluginHandler.java:97)
[06דצמ2023 08:48:33.414] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchPluginHandler$$Lambda$470/743893925.accept(Unknown Source)
[06דצמ2023 08:48:33.414] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.HashMap.forEach(HashMap.java:1280)
[06דצמ2023 08:48:33.414] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginHandler.java:97)
[06דצמ2023 08:48:33.414] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:52)
[06דצמ2023 08:48:33.414] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[06דצמ2023 08:48:33.414] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[06דצמ2023 08:48:33.414] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[06דצמ2023 08:48:33.414] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.IllegalArgumentException: The specified resource 'modid.mixin.json' was invalid or could not be read
[06דצמ2023 08:48:33.414] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1282)
[06דצמ2023 08:48:33.414] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
[06דצמ2023 08:48:33.414] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 21 more
as for the modlist, i have about 360 of em, so they might be causing it

**Comment by Gcat101** [comment] 2023-12-06 10:50
Hmmm still looks like some mod incompatibility. Please send the full modlist.

**Comment by mmmthepotatogod** [comment] 2023-12-06 17:13
ummm i guess a link could work? this way you get everything in a brand new profile to test :D (excluded stuff like texture packs, and datapacks, so its lighter)
lemme upload and see what i can do
i got a problem with curseforge now >.<
manifest would not detect a file, and i dont know which. soooo it'll take some time

**Comment by mmmthepotatogod** [comment] 2023-12-08 15:33
https://legacy.curseforge.com/minecraft/modpacks/the-multipack/files/4939643

**Comment by RealRainbuu** [comment] 2023-12-17 03:56
Fixed in latest

**Closed as completed by RealRainbuu** 2023-12-17 03:56 UTC
Labels: Bug

**Comment by mmmthepotatogod** [comment] 2023-12-17 05:59
If you dont mind me asking, what was the issue? A mod compatibility? With which?

**Comment by RealRainbuu** [comment] 2023-12-17 20:00
it was an issue on our end, nothing to do with you

**Comment by Gcat101** [comment] 2023-12-17 20:00
> If you dont mind me asking, what was the issue? A mod compatibility? With which?

mixins
